name: vip_totem
description: 'Vip Totem'
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
    # sdk: ^3.5.3
    sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
    flutter:
        sdk: flutter

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^1.0.8
    animate_do: ^3.1.2
    carousel_slider: ^5.0.0
    provider: ^6.0.0
    font_awesome_flutter: ^10.0.0
    flutter_riverpod: ^2.5.1
    flutter_masked_text2: ^0.9.1
    freezed: ^2.5.7
    json_annotation: ^4.9.0
    intl: ^0.19.0
    logger: ^2.4.0
    firebase_core: ^3.8.0
    firebase_messaging: ^15.1.3
    http: ^1.2.2
    timezone: ^0.9.4
    # flutter_local_notifications: ^17.2.3
    shared_preferences: ^2.0.8
    # workmanager: ^0.5.2
    url_launcher: ^6.3.1
    intro_slider: ^4.2.1
    flutter_native_splash: ^2.4.3
    flutter_launcher_icons: ^0.14.3
    device_info_plus: ^11.1.1
    flutter_pdfview: ^1.3.4
    path_provider: ^2.1.5
    flutter_svg: ^2.0.17
    camera: ^0.11.1
    image_picker: ^1.1.2
    permission_handler: ^11.3.1
    webview_flutter: ^4.0.0
    camera_macos: ^0.0.9
    video_player: ^2.9.3
    lottie: ^3.3.1
    http_parser: ^4.1.2
    image: ^4.5.4
    virtual_keyboard_multi_language: ^1.1.2

dependency_overrides:
    image_picker_platform_interface: ^2.10.1
    # permission_handler_macos: any

dev_dependencies:
    flutter_test:
        sdk: flutter

    # The "flutter_lints" package below contains a set of recommended lints to
    # encourage good coding practices. The lint set provided by the package is
    # activated in the `analysis_options.yaml` file located at the root of your
    # package. See that file for information about deactivating specific lint
    # rules and activating additional ones.
    flutter_lints: ^4.0.0
    build_runner: ^2.4.13
    json_serializable: ^6.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

#flutter pub run flutter_native_splash:create
flutter_native_splash:
    color: '#FFFFFF'
    image: 'assets/images/icon.png'
    android: true
    ios: true
    android_12:
        image: 'assets/images/icon.png'
        color: '#FFFFFF'
#flutter pub run flutter_launcher_icons:main
flutter_icons:
    image_path: 'assets/images/icon.png'
    ios: true
    remove_alpha_ios: true
    android: 'launcher_icon'
    adaptive_icon_background: '#FFFFFF'
    adaptive_icon_foreground: 'assets/images/icon.png'

# The following section is specific to Flutter packages.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/images/
        - assets/images/logo_verde.png
        - assets/images/splash_image.png
        - assets/images/icon.png
        - assets/images/ilustrations/
        #- assets/videos/
        - assets/fonts/
        - assets/lottie/

    fonts:
        - family: Din
          fonts:
              - asset: assets/fonts/din/din_pro_400.otf

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/to/resolution-aware-images

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/to/asset-from-package

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/to/font-from-package
